### ISSUE TITLE
[BUG] Can't build UWP

### ISSUE THREAD

**Issue by albilaga** [reactiveui/Sextant#202]
When trying to build for UWP Project using `Sextant.XamForms` I got this issue
![image](https://user-images.githubusercontent.com/2399099/73133948-8759bf80-4062-11ea-99df-1489a9992ee5.png)
Already set minimum version to 10.0 build 16299

**Comment by RLittlesII** [comment]
@albilaga Is this the UWP project for a Xamarin.Forms project?  Or a stand alone UWP project?  I ask because the packages you would need to include would be different in this scenario.

**Comment by albilaga** [comment]
@RLittlesII this is xamarin forms project.

**Comment by ericcox** [comment]
There seems to be a workaround, but my project has other problems so I haven't been able to completely test it yet.  

You have to check out the source repo, revision a2851ae493153f8b464ee23d0cca0400d4199726 (the one tagged with 2.5.1), and edit the project file Sextant.cproj in the source editor (you can't do this in the property editor because it is a multiple-platform project not a UWP project, so the 'Generate library layout' checkbox is disabled)

Add `<GenerateLibraryLayout>true</GenerateLibraryLayout>` to the first `<PropertyGroup>`, and build the solution.  (Note: I had problems building the test projects, so I just unloaded them).  This will generate the missing Sextant.xr.xaml file we need. Copy it into the folder named in the error message, and you can get your project to build.

Again I haven't been able to completely test my project to verify that it doesn't cause other problems, but this workaround got me over this hurdle.

**Comment by RLittlesII** [comment]
@ericcox Do you happen to have a reproducible sample?

Any information on the versions of UWP?
When this started? 
Has this always been an issue?

Sounds like the UWP nuget was never working based on this.

I don't use UWP often and I have limited access to Windows environments at the moment.  So any additional information around this is helpful towards a resolution.

**Comment by ericcox** [comment]
As a matter of fact I've been working on a proof of concept to get myself familiar with how the various pieces work, without having to try to integrate it into a huge 50+ project solution.  It's attached.

I'm using Windows 10 version 1809, build 17763, with target and minimum versions set to same. 

I tried rolling back to Sextant 2.4.1 and the problem no longer appeared, so I think it started with the 2.5.1 package (I had other build errors but I think that's just because the API changed).  

Not sure if it's always been an issue - just started experimenting with Sextant today :)

[xamarin-ninject-reflectui.zip](https://github.com/reactiveui/Sextant/files/4221744/xamarin-ninject-reflectui.zip)

**Comment by ericcox** [comment]
Oh - almost forgot: I have the Android/iOS projects unloaded for now - no idea if they even build.

**Comment by RLittlesII** [comment]
> I tried rolling back to Sextant 2.4.1 and the problem no longer appeared, so I think it started with the 2.5.1 package (I had other build errors but I think that's just because the API changed).

The main thing that changed was we shipped `Sextant` with a uap target package.  A UWP project using Xamarin.Forms should use the `Sextant.XamForms` package.

**Comment by RLittlesII** [comment]
@albilaga Can you confirm that the setup for the UWP app [here](https://github.com/RLittlesII/Reactive.Sandbox/tree/master/xamarin/forms/Sextant202) is setup how you are trying to setup?  If so, I was able to get a UWP target for a Xamarin.Forms application working.

**Comment by albilaga** [comment]
@RLittlesII Yes. If I am not wrong I am just using default setup app and install Sextant.XamForms and from you sample looks like it is working. Cool.

**Comment by RLittlesII** [comment]
@albilaga Great.  I apologize it took so long to get that.  I plan on putting together a few samples in the near future.  One will be using Sextant in a stand alone UWP application.  Going to close this issue.

**Comment by albilaga** [comment]
No worries. Great it is solved now 🥂
